# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/msm/Desktop/Embedded-linux-images/vsomeip/msm-examples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/msm/Desktop/Embedded-linux-images/vsomeip/msm-examples

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/msm/Desktop/Embedded-linux-images/vsomeip/msm-examples/CMakeFiles /home/msm/Desktop/Embedded-linux-images/vsomeip/msm-examples//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/msm/Desktop/Embedded-linux-images/vsomeip/msm-examples/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named msm-service

# Build rule for target.
msm-service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 msm-service
.PHONY : msm-service

# fast build rule for target.
msm-service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msm-service.dir/build.make CMakeFiles/msm-service.dir/build
.PHONY : msm-service/fast

#=============================================================================
# Target rules for targets named msm-client

# Build rule for target.
msm-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 msm-client
.PHONY : msm-client

# fast build rule for target.
msm-client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msm-client.dir/build.make CMakeFiles/msm-client.dir/build
.PHONY : msm-client/fast

src/msm-client.o: src/msm-client.cpp.o
.PHONY : src/msm-client.o

# target to build an object file
src/msm-client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msm-client.dir/build.make CMakeFiles/msm-client.dir/src/msm-client.cpp.o
.PHONY : src/msm-client.cpp.o

src/msm-client.i: src/msm-client.cpp.i
.PHONY : src/msm-client.i

# target to preprocess a source file
src/msm-client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msm-client.dir/build.make CMakeFiles/msm-client.dir/src/msm-client.cpp.i
.PHONY : src/msm-client.cpp.i

src/msm-client.s: src/msm-client.cpp.s
.PHONY : src/msm-client.s

# target to generate assembly for a file
src/msm-client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msm-client.dir/build.make CMakeFiles/msm-client.dir/src/msm-client.cpp.s
.PHONY : src/msm-client.cpp.s

src/msm-service.o: src/msm-service.cpp.o
.PHONY : src/msm-service.o

# target to build an object file
src/msm-service.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msm-service.dir/build.make CMakeFiles/msm-service.dir/src/msm-service.cpp.o
.PHONY : src/msm-service.cpp.o

src/msm-service.i: src/msm-service.cpp.i
.PHONY : src/msm-service.i

# target to preprocess a source file
src/msm-service.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msm-service.dir/build.make CMakeFiles/msm-service.dir/src/msm-service.cpp.i
.PHONY : src/msm-service.cpp.i

src/msm-service.s: src/msm-service.cpp.s
.PHONY : src/msm-service.s

# target to generate assembly for a file
src/msm-service.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msm-service.dir/build.make CMakeFiles/msm-service.dir/src/msm-service.cpp.s
.PHONY : src/msm-service.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... msm-client"
	@echo "... msm-service"
	@echo "... src/msm-client.o"
	@echo "... src/msm-client.i"
	@echo "... src/msm-client.s"
	@echo "... src/msm-service.o"
	@echo "... src/msm-service.i"
	@echo "... src/msm-service.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

